### PR TITLE
Release 1.8

### PR DESCRIPTION
**Pull request by audricschiltknecht**
This release is composed of multiple fixes and improvements from the 1.7 release:

    Merge LGR containing the same code point.
    Improve merge for metadata's description element: if all descriptions are using HTML, then output will be in HTML.
    Better display of regex for WLE in HTML output.
    Order metadata section per language then per script.
    Fix size of variant set in HTML output.
    Improve cross-script variants tool: generate the variants using the merged LGR, and list element LGRs used by the variants' code points.

### CODE REVIEW

**Comment by audricschiltknecht** [comment]
Not really sure why the tests are failling as they run fine on dev machine. Will look into that.

**Comment by audricschiltknecht** [comment]
Turns out that travis is not using the pinned dependencies from requirements.txt, as it only executes `pip install .`.

**Comment by ptudor** [comment]
Hi @audricschiltknecht , @kjd has a comment on PR #9 to please ensure python3 is supported and builds properly.

**Comment by audricschiltknecht** [comment]
Hi @ptudor,

It is very unlikely that we will be able to fix, thoroughly test and release a py3-compatible version and meet the deadline. Best path would be to release the current version with python2-only (as currently deployed), and then start working on making the fixes for a python3 version.

**Comment by wil** [comment]
@audricschiltknecht @ptudor agreed that it would be nice to make the project compatible with Python 3, and that it would take more time and testing. I made some preliminary Python 3 fixes to picu but it may have ramifications for Python 2 clients.

**Pull request merged**
